version: "3.7"

services:
  im-com:
    container_name: im-com
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
